# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiCommit < Formula
  desc "CLI tool that generates git commit messages using AI"
  homepage "https://github.com/torryt/ai-commit"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/torryt/ai-commit/releases/download/v0.1.0/ai-commit_darwin_amd64.tar.gz"
      sha256 "47a88f159709cdd7fc5c30894ea9987ba307711f445a93cb207e121c492b22d0"

      define_method(:install) do
        bin.install "ai-commit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/torryt/ai-commit/releases/download/v0.1.0/ai-commit_darwin_arm64.tar.gz"
      sha256 "0a95e7b1462897888324b8732e4240171d42764a8afb20e107f5469e52b3f4cb"

      define_method(:install) do
        bin.install "ai-commit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/torryt/ai-commit/releases/download/v0.1.0/ai-commit_linux_amd64.tar.gz"
      sha256 "1dc9641b50bce805293345f21fa563dd40df94bda3040a9099a124292b57310a"
      define_method(:install) do
        bin.install "ai-commit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/torryt/ai-commit/releases/download/v0.1.0/ai-commit_linux_arm64.tar.gz"
      sha256 "e5f6755fe99d273c055c8a0bf2ff4c0d89779340e4953f5d5ec7962d3c5e02cb"
      define_method(:install) do
        bin.install "ai-commit"
      end
    end
  end

  test do
    system "#{bin}/ai-commit", "--version"
  end
end
