# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Riff < Formula
  desc "Disposable, throwaway project workspaces"
  homepage "https://github.com/torryt/riff"
  version "0.1.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/torryt/riff/releases/download/v0.1.16/riff_darwin_amd64.tar.gz"
      sha256 "b5948f9d5229bee675554ded276acc81c2664d0fb02143123874e1ca79965471"

      define_method(:install) do
        bin.install "riff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/torryt/riff/releases/download/v0.1.16/riff_darwin_arm64.tar.gz"
      sha256 "84d45d2ca80a6d7e2a4b350fc59d6c909d4ea881a6346ee4093c26e07063d5c7"

      define_method(:install) do
        bin.install "riff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/torryt/riff/releases/download/v0.1.16/riff_linux_amd64.tar.gz"
      sha256 "1ec773ad925359f7115ceb9d0c9aa8a41064b3a7d31be5ea7c35761fc94db321"
      define_method(:install) do
        bin.install "riff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/torryt/riff/releases/download/v0.1.16/riff_linux_arm64.tar.gz"
      sha256 "c14fc3e9e98f1c42070e9fe9be035ee707befc0bd4265d5b6f69a8b1a2a9e48d"
      define_method(:install) do
        bin.install "riff"
      end
    end
  end

  test do
    system "#{bin}/riff", "version"
  end
end
